/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillRouteImport } from './routes/skill'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as My_productsRouteImport } from './routes/my_products'
import { Route as IndexRouteImport } from './routes/index'

const SkillRoute = SkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const My_productsRoute = My_productsRouteImport.update({
  id: '/my_products',
  path: '/my_products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my_products': typeof My_productsRoute
  '/policy': typeof PolicyRoute
  '/skill': typeof SkillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my_products': typeof My_productsRoute
  '/policy': typeof PolicyRoute
  '/skill': typeof SkillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my_products': typeof My_productsRoute
  '/policy': typeof PolicyRoute
  '/skill': typeof SkillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my_products' | '/policy' | '/skill'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my_products' | '/policy' | '/skill'
  id: '__root__' | '/' | '/my_products' | '/policy' | '/skill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  My_productsRoute: typeof My_productsRoute
  PolicyRoute: typeof PolicyRoute
  SkillRoute: typeof SkillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skill': {
      id: '/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof SkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my_products': {
      id: '/my_products'
      path: '/my_products'
      fullPath: '/my_products'
      preLoaderRoute: typeof My_productsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  My_productsRoute: My_productsRoute,
  PolicyRoute: PolicyRoute,
  SkillRoute: SkillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
